spring.application.name=pieca-backend

# --- Multipart Upload ---
spring.servlet.multipart.max-file-size=6MB
spring.servlet.multipart.max-request-size=6MB

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=false

spring.devtools.add-properties=false